### ISSUE TITLE
twitch.tv ad stub

### ISSUE THREAD

**Issue by Xost3r** [AdguardTeam/AdGuardExtra#422] opened 2023-03-22 15:07 UTC
sorry i am writing using google translate

1-While watching a broadcast on twitch, a wave of advertisements suddenly comes and adguard blocks the extra advertisement, but instead of the advertisement, a screen like the video appears, which is no different from the advertisement.

The second problem is that the broadcast freezes after a while, but there is no problem with the internet. You can see more details in the video.

vid: https://drive.google.com/file/d/1AJjm8RlJTAVghMiIYD3wvxcbubPm4rrK

**Comment by stanislav-atr** [comment] 2023-03-22 15:18
@Xost3r, hi! This advertisement stub is known and yet to be reproduced. It seems that twitch only applies some of the ads to a small portion of users.

@AdamWr @zloyden check this out, please.

**Comment by AdamWr** [comment] 2023-03-23 08:53
I cannot reproduce it at the moment, but I occasionally see this message.

**Comment by Zoxjib** [comment] 2023-04-09 15:07
Having the same issue now. I've had it recur many times this week while a stream is running in the background for many hours (twitch drops). 

Switching to another stream seems to solve the problem.

**Comment by lejifps** [comment] 2023-06-30 18:49
+++ got the same issue

also my streams are laggy puffering every few seconds ... driving me nuts

**Comment by Mo-norn** [comment] 2023-07-05 06:49
Is this still difficult to reproduce?
It seems to be reproducible from a South Korea IP.
I was also able to reproduce it in browser incognito mode, not signed in.
I recently disconnected Adguard to see if it was fixed, but I was able to watch Twitch without any issues. I don't think there were any Twitch country ads during that time.
It may be difficult to reproduce perfectly in a short period of time because it depends on the duration of the ad or the streamer's ad settings.
I think it should be reproducible with a South Korea IP and a Korean streamers.

**Comment by stanislav-atr** [comment] 2023-08-02 17:17
Moving this into #383

**Closed** 2023-08-02 17:18 UTC
Labels: Resolution: Duplicate, Status: Resolved, Priority: P4
