### ISSUE TITLE
JavaScript error in "AdGuard Extra.user.js" (Invalid attempt to spread non-iterable instance)

### ISSUE THREAD

**Issue by RubaXa** [AdguardTeam/AdGuardExtra#105] opened 2020-08-27 13:46 UTC
**Steps to reproduce**
- Install AdGuard Assistant for Safari
- Open octavius.mail.ru

**Expected behavior**
- No errors should happen

**Actual behavior**

- UserAgent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15`
- Script: `AdGuard-Extra.user.js`

```
TypeError: TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
             _nonIterableSpread
             forEach@[native code]
             iterateCSSRules
             hideRulesByCondition
```

**Because**

```js
 function safeGetStylesheetRules(sheet) {
    try {
        return sheet.rules;   // <--- rules - can be `null` 🐞 
    } catch (e) {
        return [];
    }
}
```

**This can be fixed by adding a check for `null` and `undefined` to the method `_toConsumableArray`**:

```js
function _toConsumableArray(arr) {
    if (arr == null) { // <!-- fix ⚠️
        return [];
    }

    return arrayWithoutHoles(arr) || iterableToArray(arr) || unsupportedIterableToArray(arr) || nonIterableSpread();
}
```

**Comment by zloyden** [comment] 2020-08-31 08:32
Hello! I can't reproduce this issue with your `steps to reproduce`.
@tvinzz please take a look at your end.

**Comment by RubaXa** [comment] 2020-08-31 08:45
But it is, moreover, a lot (~1K errors per min per user):

- ![image](https://user-images.githubusercontent.com/1109562/91700617-da5a9e80-eb7e-11ea-81cb-85383072997e.png)

- ![image](https://user-images.githubusercontent.com/1109562/91700855-2574b180-eb7f-11ea-8eea-60d5865e5ec2.png)

**Comment by zloyden** [comment] 2020-08-31 16:00
@RubaXa that was strange today, I was able to reproduce it. Will be fixed.

**Closed** 2020-09-01 12:09 UTC
Labels: Resolution: Fixed, Status: Resolved
