### ISSUE TITLE
Add support for YouTube and YT Music

### ISSUE THREAD

**Issue by Mlocik97** [AdguardTeam/AdGuardExtra#316] opened 2022-04-24 13:58 UTC
YouTube is working hard to force us ads... It even play ad in middle of song. (Happend just minute ago), as I look on YouTube's client-side code, I can see scripts that are trying to block Adblockers such as Adguard... would be nice to do something with it.

**Comment by stanislav-atr** [comment] 2022-04-25 12:11
@Mlocik97, hi! What AdGuard product do you use? I don't experience any issues right now with AdGuard adblocker browser extension and Extra. Please, don't forget, that Extra is complimentary userscript and should be used with over AdGuard products.

**Comment by Mlocik97** [comment] 2022-04-25 13:44
I use Adguard extension for Chrome and Firefox, 

version: 4.0.163
chrome: 100.0.4896.127
firefox: 99.0
system: Ubuntu 20.04.4 LTS

**Comment by zloyden** [comment] 2022-04-27 12:35
I've been listening to music on Youtube for a long time and can't reproduce ads.
Try to clear browser data, update filters and extra, then check the playlist again.

**Comment by Mlocik97** [comment] 2022-04-27 12:41
I also use YouTube NonStop extension <https://chrome.google.com/webstore/detail/youtube-nonstop/nlkaejimjacpillmajjnopmpbkbnocid>.

**Comment by stanislav-atr** [comment] 2022-05-11 09:37
@Mlocik97 do ads appear if you turn this extension off? Is there other third-party extensions or userscripts you use?

**Comment by Mlocik97** [comment] 2022-05-11 10:29
last week I didn't get any ads, btw. I have Adguard, AdGuard Extra and YouTube NonStop.. nothing else... all enabled.

**Comment by stanislav-atr** [comment] 2022-05-11 10:32
@Mlocik97, ok, thanks for the reply. I will be closing this issue now, feel free to reopen it with ads screenshots and/or third-party extensions you are using.

**Closed** 2022-05-11 10:40 UTC
